// Code generated by hero.
// source: /home/strannik/www/presentation-builder/templates/upload.html
// DO NOT EDIT!
package template

import "bytes"

func Upload(buffer *bytes.Buffer) {
	buffer.WriteString(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Presentation builder</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css">
   
  </head>
  <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <a class="navbar-brand" href="/">Presentation builder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/presentations">My presentations</a>
                    </li>                    
                    <li class="nav-item">
                      <a class="nav-link" href="/upload">New upload</a>
                    </li>                    
                  </ul>
                  
                </div>
              </nav>
              
              <main role="main" class="container">
        `)
	buffer.WriteString(`
    <form class="form-signin" method="POST" enctype=multipart/form-data>       
        <h1 class="h3 mb-3 font-weight-normal">Upload PDF</h1>
        <label for="inputEmail" class="sr-only">PDF file</label>
        <input type="file" id="file" name="file" class="form-control" placeholder="PDF file" required autofocus accept="application/pdf">        
        <button class="btn btn-lg btn-primary btn-block" type="submit">Upload</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
    </form>
`)

	buffer.WriteString(`
        </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>
`)

}
